"""Constantes de UI para la GUI Qt."""

SIDEBAR_WIDTH = 230
SIDEBAR_MARGIN = 16
SIDEBAR_SPACING = 10
FLOW_CARD_MARGIN = 8
FLOW_CARD_SPACING = 6
STATUS_BAR_HEIGHT = 30
STATUS_BAR_MARGIN_H = 12
STATUS_BAR_MARGIN_V = 4
STATUS_BAR_SPACING = 10
STATUS_PROGRESS_WIDTH = 180
